### PR TITLE
Rebuild testing

### PR DESCRIPTION
**Pull request by stefanpenner**
this depends on https://github.com/joliss/node-fixturify/pull/1

### CODE REVIEW

**Comment by stefanpenner** [comment]
This will most likely need to be reworked, as https://github.com/joliss/node-fixturify/issues/1 has changed some.

**Comment by stefanpenner** [comment]
Given https://github.com/rwjblue/broccoli-fixturify/pull/6 changed, I'll need to fix this PR up

**Comment by rwjblue** [comment]
Sounds good, ping me when its ready for review again...

**Comment by stefanpenner** [comment]
I have decided to just use node-fixturify directly, I found it is slightly more boiler plate but way the lack of abstraction made my tests clear. That doesn't mean we can't improve it, but I found the indirection here made me think about the system less concretely .

**Comment by stefanpenner** [comment]
node-fixturify directly:

https://github.com/broccolijs/broccoli-funnel/blob/master/tests/index.js#L26-L27

used in:

https://github.com/broccolijs/broccoli-funnel/blob/master/tests/index.js#L61-L62

**Comment by stefanpenner** [comment]
One reason I abandoned this PR was when adding "rebuild" testing, I realized I just wanted to use fixturify directly, which made me questions the indirection.  Although I could be convinced, the above pattern has been my sufficiently happy and productive that I haven't felt compelled to push this forward.

**Pull request closed without merging**
